--- 
jobs: 
  - 
    job: Test
    pool: 
      vmImage: ubuntu-latest
    steps: 
      - 
        displayName: "Use Python $(python.version)"
        inputs: 
          versionSpec: $(python.version)
        task: UsePythonVersion@0
      - 
        script: "python -m pip install --upgrade pip setuptools wheel"
      - 
        script: "python -m pip install --upgrade pytest"
      - 
        script: "python -m pip install --upgrade selenium"
      - 
        script: "python -m pip install --upgrade allure-pytest"
      - 
        script: "python -m pip install --upgrade xlrd"
      - 
        script: "python -m pip install --upgrade webdriver_manager"
      - 
        script: |
            python -m pytest tests/PaytmSignIn.py
            displayName: <s>'pytest'</s>
    strategy: 
      matrix: 
        Python39: 
          python.version: "3.9"
