
trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  
- task: PowerShell@2
  displayName: "show configuration"
  inputs:
    targetType: "inline"
    script: |
      #debug
      cat config.json
  

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'Sample1/s2.py'