
trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

   - script: python -m pip install --upgrade pip setuptools wheel
   - script: python -m pip install --upgrade pytest
   - script: python -m pip install --upgrade selenium
   - script: python -m pip install --upgrade allure-pytest
   - script: python -m pip install --upgrade xlrd
   - script: python -m pip install --upgrade webdriver_manager
   
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'tests/PaytmSignIn.py'